export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_PETES_EVENTS_START = 'GET_PETES_EVENTS_START';
export const GET_PETES_EVENTS_SUCCESS = 'GET_PETES_EVENTS_SUCCESS';
export const GET_PETES_EVENTS_FAIL = 'GET_PETES_EVENTS_FAIL';

export const GET_PINE_EVENTS_START = 'GET_PINE_EVENTS_START';
export const GET_PINE_EVENTS_SUCCESS = 'GET_PINE_EVENTS_SUCCESS';
export const GET_PINE_EVENTS_FAIL = 'GET_PINE_EVENTS_FAIL';

export const ADD_SHOW_START = 'ADD_SHOW_START';
export const ADD_SHOW_SUCCESS = 'ADD_SHOW_SUCCESS';
export const ADD_SHOW_FAIL = 'ADD_SHOW_FAIL';
export const REMOVE_SHOW = 'REMOVE_SHOW';
export const EDIT_SHOW = 'EDIT_SHOW';
export const GET_SHOWS_START = 'GET_SHOWS_START';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_SHOWS_FAIL = 'GET_SHOWS_FAIL';

export const ADD_POST_START = 'ADD_POST_START';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const REMOVE_POST = 'REMOVE_POST';
export const EDIT_POST = 'EDIT_POST';
export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const GET_YOUTUBE_PLAYLIST_START = 'GET_YOUTUBE_PLAYLIST_START';
export const GET_YOUTUBE_PLAYLIST_SUCCESS = 'GET_YOUTUBE_PLAYLIST_SUCCESS';
export const GET_YOUTUBE_PLAYLIST_FAIL = 'GET_YOUTUBE_PLAYLIST_FAIL';
